import numpy as np
import torch
import pandas as pd
import os

def X_to_tensor(X, device=None) -> torch.Tensor:
    """Transform input data X to a PyTorch tensor and performs normalization.

    Args:
        X (array-like or pandas.DataFrame): Input data.
        device (torch.device): Device on which to create the tensor. If None, the tensor will be created on the default device.

    Returns:
        torch.Tensor: Normalized input data as a PyTorch tensor.
    """
    if isinstance(X, np.ndarray):
        X = torch.from_numpy(X).type(torch.float64)
    elif isinstance(X, pd.DataFrame):
        X = torch.from_numpy(X.values).type(torch.float64)
    else:
        X = torch.as_tensor(X, dtype=torch.float64)
    if device:
        X = X.to(device)
    norms = torch.norm(X, p=2, dim=0)
    X = X / norms
    return X

def y_to_tensor(y, device=None) -> torch.Tensor:
    """Convert target data y to a PyTorch tensor.

    Args:
        y (array-like or pandas.DataFrame): Target data.
        device (torch.device, optional): Device on which to create the tensor. If None, the tensor will be created on the default device.

    Returns:
        torch.Tensor: Target data as a PyTorch tensor.
    """
    if isinstance(y, np.ndarray):
        y = torch.from_numpy(y).type(torch.float64)
    elif isinstance(y, pd.Series) or isinstance(y, pd.DataFrame):
        y = torch.from_numpy(y.values.squeeze()).type(torch.float64)
    else:
        y = torch.as_tensor(y, dtype=torch.float64)
    if device:
        y = y.to(device)
    return y


def data_to_tensor(X, y, device=None) -> tuple[torch.Tensor, torch.Tensor]:
    """Convert input data X and target data y to a PyTorch tensor.

    Args:
        X (array-like or pandas.DataFrame): Input data.
        y (array-like or pandas.DataFrame): Target data.
        device (torch.device, optional): Device on which to create the tensors. If None, the tensors will be created on the default device.

    Returns:
        torch.Tensor: Normalized input data as a PyTorch tensor.
        torch.Tensor: Target data as a PyTorch tensor.
    """
    X = X_to_tensor(X, device)
    y = y_to_tensor(y, device)
    return X, y


def generate_linear_data(save_dir, n_train=100, n_val=30, n_test=300, p1=200, SNR=3):
    """Generates linearly separable data with a given signal-to-noise ratio (SNR). 
    The data is generated by first generating random normal variables for the input data and the target data. 
    The SNR is then applied to the input data, and the resulting data is combined with noise to create the target data.
    The data is saved in separate CSV files in the given directory. The important indices for each SNR are also saved as a CSV file.


    Args:
        save_dir (str, optional): Directory where the data should be saved.
        n_train (int, optional): Number of samples for the training dataset.. Defaults to 100.
        n_val (int, optional): Number of samples for the validation dataset.. Defaults to 30.
        n_test (int, optional): Number of samples for the test dataset.. Defaults to 300.
        p1 (int, optional): Number of input features.. Defaults to 200.
        SNR (int, optional): Signal-to-noise ratio. Defaults to 3.

    Raises:
        ValueError: If no save directory has been given.
        TypeError: If the save directory is not a string.
    """
    
    if save_dir is None:
        raise ValueError("No file directory has been given")
    if not isinstance(save_dir, str):
        raise TypeError("File directory must be a string")


    for s in range(1, 18):
        beta = SNR * np.ones(s)
        inds = np.random.choice(range(p1), s, replace=False)
        datasets = {} 

        for n, name in zip([n_train, n_val, n_test], ['train', 'val', 'test']):
            x = np.random.normal(size=(n, p1))
            y = np.dot(x[:, inds], beta) + np.random.normal(size=(n))
            datasets[name] = [pd.DataFrame(x), pd.DataFrame(y)]

        s_dir = os.path.join(save_dir, f"s{s}")
        os.makedirs(s_dir, exist_ok=True)
        
        for name in ['train', 'val', 'test']:
            x, y = datasets[name]
            x.to_csv(os.path.join(s_dir, f"{name}-x.csv"), header=False, index=False)
            y.to_csv(os.path.join(s_dir, f"{name}-y.csv"), header=False, index=False)

        inds_df = pd.DataFrame(inds)
        inds_df.to_csv(os.path.join(s_dir, f"important_inds.csv"), index=False)

        print(f"Data for s={s} saved in directory: {s_dir}")
